# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import service_pb2 as proto_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScriptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScriptSync = channel.unary_unary(
                '/scriptservice.ScriptService/ExecuteScriptSync',
                request_serializer=proto_dot_service__pb2.ScriptRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ScriptResponseSync.FromString,
                _registered_method=True)
        self.ExecuteScriptAsync = channel.unary_unary(
                '/scriptservice.ScriptService/ExecuteScriptAsync',
                request_serializer=proto_dot_service__pb2.ScriptRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ScriptResponseAsync.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/scriptservice.ScriptService/GetStatus',
                request_serializer=proto_dot_service__pb2.StatusRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/scriptservice.ScriptService/GetResult',
                request_serializer=proto_dot_service__pb2.ResultRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ScriptResponseSync.FromString,
                _registered_method=True)


class ScriptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteScriptSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScriptAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScriptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScriptSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScriptSync,
                    request_deserializer=proto_dot_service__pb2.ScriptRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ScriptResponseSync.SerializeToString,
            ),
            'ExecuteScriptAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScriptAsync,
                    request_deserializer=proto_dot_service__pb2.ScriptRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ScriptResponseAsync.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=proto_dot_service__pb2.StatusRequest.FromString,
                    response_serializer=proto_dot_service__pb2.StatusResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=proto_dot_service__pb2.ResultRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ScriptResponseSync.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scriptservice.ScriptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scriptservice.ScriptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScriptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteScriptSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scriptservice.ScriptService/ExecuteScriptSync',
            proto_dot_service__pb2.ScriptRequest.SerializeToString,
            proto_dot_service__pb2.ScriptResponseSync.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteScriptAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scriptservice.ScriptService/ExecuteScriptAsync',
            proto_dot_service__pb2.ScriptRequest.SerializeToString,
            proto_dot_service__pb2.ScriptResponseAsync.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scriptservice.ScriptService/GetStatus',
            proto_dot_service__pb2.StatusRequest.SerializeToString,
            proto_dot_service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scriptservice.ScriptService/GetResult',
            proto_dot_service__pb2.ResultRequest.SerializeToString,
            proto_dot_service__pb2.ScriptResponseSync.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
