# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\rscriptservice\",\n\rScriptRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\"X\n\x12ScriptResponseSync\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0f\n\x07\x65xec_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0e\n\x06stderr\x18\x04 \x01(\t\"&\n\x13ScriptResponseAsync\x12\x0f\n\x07\x65xec_id\x18\x01 \x01(\t\" \n\rStatusRequest\x12\x0f\n\x07\x65xec_id\x18\x01 \x01(\t\"H\n\x0eStatusResponse\x12\x0f\n\x07\x65xec_id\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.scriptservice.Status\" \n\rResultRequest\x12\x0f\n\x07\x65xec_id\x18\x01 \x01(\t*J\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x32\xd5\x02\n\rScriptService\x12T\n\x11\x45xecuteScriptSync\x12\x1c.scriptservice.ScriptRequest\x1a!.scriptservice.ScriptResponseSync\x12V\n\x12\x45xecuteScriptAsync\x12\x1c.scriptservice.ScriptRequest\x1a\".scriptservice.ScriptResponseAsync\x12H\n\tGetStatus\x12\x1c.scriptservice.StatusRequest\x1a\x1d.scriptservice.StatusResponse\x12L\n\tGetResult\x12\x1c.scriptservice.ResultRequest\x1a!.scriptservice.ScriptResponseSyncb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=356
  _globals['_STATUS']._serialized_end=430
  _globals['_SCRIPTREQUEST']._serialized_start=38
  _globals['_SCRIPTREQUEST']._serialized_end=82
  _globals['_SCRIPTRESPONSESYNC']._serialized_start=84
  _globals['_SCRIPTRESPONSESYNC']._serialized_end=172
  _globals['_SCRIPTRESPONSEASYNC']._serialized_start=174
  _globals['_SCRIPTRESPONSEASYNC']._serialized_end=212
  _globals['_STATUSREQUEST']._serialized_start=214
  _globals['_STATUSREQUEST']._serialized_end=246
  _globals['_STATUSRESPONSE']._serialized_start=248
  _globals['_STATUSRESPONSE']._serialized_end=320
  _globals['_RESULTREQUEST']._serialized_start=322
  _globals['_RESULTREQUEST']._serialized_end=354
  _globals['_SCRIPTSERVICE']._serialized_start=433
  _globals['_SCRIPTSERVICE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
